/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ma_schleemilch_dynlibjava_MyNdk */

#ifndef _Included_ma_schleemilch_dynlibjava_MyNdk
#define _Included_ma_schleemilch_dynlibjava_MyNdk
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ma_schleemilch_dynlibjava_MyNdk
 * Method:    printSuccess
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ma_schleemilch_dynlibjava_MyNdk_printSuccess
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
