/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class schleemilch_ma_nativememory_MyNDK */

#ifndef _Included_schleemilch_ma_nativememory_MyNDK
#define _Included_schleemilch_ma_nativememory_MyNDK
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     schleemilch_ma_nativememory_MyNDK
 * Method:    showSelfProc
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_schleemilch_ma_nativememory_MyNDK_showSelfProc
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
