/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ma_schleemilch_nativestuff_MyNDK */

#ifndef _Included_ma_schleemilch_nativestuff_MyNDK
#define _Included_ma_schleemilch_nativestuff_MyNDK
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ma_schleemilch_nativestuff_MyNDK
 * Method:    showProcSpace
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ma_schleemilch_nativestuff_MyNDK_showProcSpace
  (JNIEnv *, jobject);

/*
 * Class:     ma_schleemilch_nativestuff_MyNDK
 * Method:    libExe
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_ma_schleemilch_nativestuff_MyNDK_libExe
  (JNIEnv *, jobject, jstring);

/*
 * Class:     ma_schleemilch_nativestuff_MyNDK
 * Method:    binExe
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_ma_schleemilch_nativestuff_MyNDK_binExe
  (JNIEnv *, jobject, jstring);

/*
 * Class:     ma_schleemilch_nativestuff_MyNDK
 * Method:    callNativeActivity
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_ma_schleemilch_nativestuff_MyNDK_callNativeActivity
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
