/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ma_schleemilch_nativememoryaccess_MyNDK */

#ifndef _Included_ma_schleemilch_nativememoryaccess_MyNDK
#define _Included_ma_schleemilch_nativememoryaccess_MyNDK
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ma_schleemilch_nativememoryaccess_MyNDK
 * Method:    showProcSpace
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ma_schleemilch_nativememoryaccess_MyNDK_showProcSpace
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
